### ISSUE TITLE
LrkFM 1.6.2: App crashes when changing header unit in UI settings

### ISSUE THREAD

**Issue by mcyusuf** [lfuelling/lrkFM#10]
#### Expected behavior
While trying to change the header unit in the UI options in settings from mebibyte to gibibyte, a crash shouldn't occur.

#### Actual behavior
On changing the header unit in UI settings, the app stops working.

#### How to reproduce
1. Open the side menu of the app
2. Select settings, then UI option
3. Click on unit to use in header
4. Change the unit from mebibyte to gibibyte.

***
* Browser/App version: lrkfm 1.6.2
* Operating system: Android Nougat 7.0
***
#### Recording Of The Bug
![20180515_152303.gif](https://steemitimages.com/DQmVqSnoDdhepX2VRGKMVzuM4gjUyBvZ6YEoeMJTmJzu81r/20180515_152303.gif)

#### LogCat
```
05-15 15:19:29.074 E/Fabric  (25532): Settings request failed.
05-15 15:19:29.337 E/MPlugin (25532): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-15 15:19:29.575 E/        (25532): appName=io.lerk.lrkFM, acAppName=/system/bin/surfaceflinger
05-15 15:19:29.575 E/        (25532): 0
05-15 15:19:29.839 D/NetworkController.MobileSignalController(3)(  932): onSignalStrengthsChanged signalStrength=SignalStrength: 8 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte 74 -356 14 level=4
05-15 15:19:29.839 D/NetworkController.MobileSignalController(3)(  932): updateTelephonySignalStrength: hasService=true ss=SignalStrength: 8 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte 74 -356 14
05-15 15:19:30.196 E/CrashlyticsCore(25532): Error occurred sending report com.crashlytics.android.core.SessionReport@6e432cd
05-15 15:19:30.200 E/CrashlyticsCore(25532): Error occurred sending report com.crashlytics.android.core.SessionReport@dbe3e93
05-15 15:19:32.453 E/WifiStateMachine(  796): mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
05-15 15:19:32.471 E/WifiScanningService(  796): WifiSingleScanStateMachine IdleState enter
05-15 15:19:32.876 E/ActivityThread(25605): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
05-15 15:19:32.921 E/ActivityThread(25605): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
05-15 15:19:33.139 E/MPlugin (25647): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-15 15:19:33.610 E/WifiStateMachine(  796): mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
05-15 15:19:33.612 E/WifiScanningService(  796): WifiSingleScanStateMachine IdleState enter
05-15 15:19:36.006 E/FirebaseCrash(25532): Error sending crash report: IOException while sending a crash report
05-15 15:19:37.300 E/FirebaseCrash(25532): Error sending crash report: IOException while sending a crash report
05-15 15:19:37.508 D/NetworkController.MobileSignalController(3)(  932): onSignalStrengthsChanged signalStrength=SignalStrength: 14 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte 72 -336 11 level=4
05-15 15:19:37.508 D/NetworkController.MobileSignalController(3)(  932): updateTelephonySignalStrength: hasService=true ss=SignalStrength: 14 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte 72 -336 11
05-15 15:19:38.221 E/UncaughtException(25532): 
05-15 15:19:38.221 E/UncaughtException(25532): java.lang.NullPointerException
05-15 15:19:38.221 E/UncaughtException(25532): 	at java.util.Objects.requireNonNull(Objects.java:203)
05-15 15:19:38.221 E/UncaughtException(25532): 	at io.lerk.lrkFM.activities.SettingsActivity.lambda$setOnPreferenceChangeListener$0(SettingsActivity.java:185)
05-15 15:19:38.221 E/UncaughtException(25532): 	at io.lerk.lrkFM.activities.-$$Lambda$SettingsActivity$zv5HVfkWlta-QC9gXeq_Kq5DTBk.onPreferenceChange(lambda)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.preference.Preference.callChangeListener(Preference.java:965)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1409)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.os.Looper.loop(Looper.java:203)
05-15 15:19:38.221 E/UncaughtException(25532): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
05-15 15:19:38.221 E/UncaughtException(25532): 	at java.lang.reflect.Method.invoke(Native Method)
05-15 15:19:38.221 E/UncaughtException(25532): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-15 15:19:38.221 E/UncaughtException(25532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-15 15:19:38.627 E/AndroidRuntime(25532): FATAL EXCEPTION: main
05-15 15:19:38.627 E/AndroidRuntime(25532): Process: io.lerk.lrkFM, PID: 25532
05-15 15:19:38.627 E/AndroidRuntime(25532): java.lang.NullPointerException
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at java.util.Objects.requireNonNull(Objects.java:203)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at io.lerk.lrkFM.activities.SettingsActivity.lambda$setOnPreferenceChangeListener$0(SettingsActivity.java:185)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at io.lerk.lrkFM.activities.-$$Lambda$SettingsActivity$zv5HVfkWlta-QC9gXeq_Kq5DTBk.onPreferenceChange(lambda)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.preference.Preference.callChangeListener(Preference.java:965)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1409)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.os.Looper.loop(Looper.java:203)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at java.lang.reflect.Method.invoke(Native Method)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-15 15:19:38.627 E/AndroidRuntime(25532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-15 15:19:39.894 E/FirebaseCrash(25532): Error sending crash report: IOException while sending a crash report
05-15 15:19:40.382 E/ActivityManager(  796): Found activity ActivityRecord{b08f9d u0 io.lerk.lrkFM/.activities.SettingsActivity t2281 f} in proc activity list using null instead of expected ProcessRecord{45e494e 25532:io.lerk.lrkFM/u0a216}
05-15 15:19:40.519 E/JavaBinder(  796): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
05-15 15:19:40.522 E/JavaBinder(  796): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 108)
05-15 15:19:40.536 E/InputDispatcher(  796): channel '3cc3875 io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-15 15:19:40.536 E/InputDispatcher(  796): channel '96aae4b io.lerk.lrkFM/io.lerk.lrkFM.activities.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-15 15:19:40.536 E/InputDispatcher(  796): channel 'f55d900 io.lerk.lrkFM/io.lerk.lrkFM.activities.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by mcyusuf** [comment]
Good. That's a quick fix on v1.6.4. thanks.
