### ISSUE TITLE
LrkFM 1.6.4: App crashes as it tries to go beyond the device root folder.

### ISSUE THREAD

**Issue by mcyusuf** [lfuelling/lrkFM#14]
#### Expected behavior
Taking the directory back to a parent folder making use of the arrow cap icon at the bottom right, when the device root folder is reached it isn't suppose to go any further. There shouldn't be any more activity to perform beyond that.

#### Actual behavior
On going back the directory levels and reaching the root folder _/_, the application crashes when the icon is tapped again. 

#### How to reproduce
1. On the app main page showing the files, make use of the arrow cap icon at the bottom right to go back the directory levels till the root folder is reached.
2. You can check the current folder by looking at the top of the side menu.
3. Try to go back again using that icon and app will crash.

* App version: 1.6.4
* Device: Tecno K7
* Operating system: Android Nougat 7.0

#### LogCat
```
build.device: TECNO-K7
version.release: 7.0

05-17 18:25:09.417 I/ActivityManager(800): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.lerk.lrkFM/.activities.FileActivity bnds=[290,820][430,1013] (has extras)} from uid 10022 on display 0
05-17 18:25:09.470 I/BufferQueueConsumer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:0,p:-1,c:224) setConsumerName: Starting io.lerk.lrkFM
05-17 18:25:09.470 I/BufferQueueConsumer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:0,p:-1,c:224) setDefaultBufferSize: width=1 height=1
05-17 18:25:09.481 I/ActivityManager(800): Start proc 16738:io.lerk.lrkFM/u0a216 for activity io.lerk.lrkFM/.activities.FileActivity
05-17 18:25:09.484 I/BufferQueueConsumer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-17 18:25:09.496 I/BufferQueueProducer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:2,p:800,c:224) connect(P): api=2 producer=(800:system_server) producerControlledByApp=false
05-17 18:25:09.498 I/BufferQueueProducer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:2,p:800,c:224) new GraphicBuffer needed
05-17 18:25:09.548 I/libPerfService(800): [perfNotifyAppState] foreground:io.lerk.lrkFM, pid:16738
05-17 18:25:09.549 I/PPS     (800): [PPSNotifyAppState] pack:io.lerk.lrkFM, com:io.lerk.lrkFM.activities.FileActivity, state:1,ActiveCount = 1
05-17 18:25:09.549 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:io.lerk.lrkFM, com:io.lerk.lrkFM.activities.FileActivity, state:1, pid:16738, last_boost_tid:16738
05-17 18:25:09.685 W/System  (16738): ClassLoader referenced unknown path: /data/app/io.lerk.lrkFM-1/lib/arm
05-17 18:25:10.173 I/FA      (16738):   adb shell setprop debug.firebase.analytics.app io.lerk.lrkFM
05-17 18:25:10.779 I/NotificationService(800): enqueueToast pkg=io.lerk.lrkFM callback=android.app.ITransientNotification$Stub$Proxy@f4cc173 duration=0
05-17 18:25:10.909 I/BufferQueueConsumer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:0,p:-1,c:224) setConsumerName: io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity
05-17 18:25:10.909 I/BufferQueueConsumer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:0,p:-1,c:224) setDefaultBufferSize: width=1 height=1
05-17 18:25:10.925 I/BufferQueueConsumer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-17 18:25:11.037 E/        (16738): appName=io.lerk.lrkFM, acAppName=/system/bin/surfaceflinger
05-17 18:25:11.104 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) connect(P): api=1 producer=(16738:io.lerk.lrkFM) producerControlledByApp=true
05-17 18:25:11.106 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-17 18:25:11.238 I/BufferQueueProducer(224): [Toast](this:0xab427000,id:1360,api:1,p:16738,c:224) connect(P): api=1 producer=(16738:io.lerk.lrkFM) producerControlledByApp=true
05-17 18:25:11.274 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) new GraphicBuffer needed
05-17 18:25:11.340 I/ActivityManager(800): Displayed io.lerk.lrkFM/.activities.FileActivity: +1s878ms
05-17 18:25:11.365 I/WindowManager(800): Destroying surface Surface(name=Starting io.lerk.lrkFM) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.AppWindowToken.destroySurfaces:372 com.android.server.wm.WindowStateAnimator.finishExit:586 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:512 com.android.server.wm.WindowAnimator.updateWindowsLocked:319 com.android.server.wm.WindowAnimator.animateLocked:720 
05-17 18:25:11.367 I/BufferQueueProducer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:2,p:-1,c:224) disconnect(P): api 2
05-17 18:25:11.367 I/BufferQueueConsumer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:2,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-17 18:25:11.382 I/BufferQueueConsumer(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:2,p:-1,c:-1) disconnect(C)
05-17 18:25:11.382 I/BufferQueue(224): [Starting io.lerk.lrkFM](this:0xaee5e000,id:1358,api:2,p:-1,c:-1) ~BufferQueueCore
05-17 18:25:11.408 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) new GraphicBuffer needed
05-17 18:25:11.428 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) new GraphicBuffer needed
05-17 18:25:11.472 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) new GraphicBuffer needed
05-17 18:25:12.886 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) queueBuffer: fps=5.13 dur=1560.79 max=1371.90 min=10.05
05-17 18:25:14.171 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) queueBuffer: fps=12.44 dur=1285.75 max=1023.01 min=12.90
05-17 18:25:14.192 W/io.lerk.lrkFM.activities.FileActivity(16738): Can't read '/storage/emulated': Permission denied!
05-17 18:25:14.198 I/NotificationService(800): enqueueToast pkg=io.lerk.lrkFM callback=android.app.ITransientNotification$Stub$Proxy@2e93fb6 duration=0
05-17 18:25:14.294 I/BufferQueueProducer(224): [Toast](this:0xaee5e000,id:1361,api:1,p:16738,c:224) connect(P): api=1 producer=(16738:io.lerk.lrkFM) producerControlledByApp=true
05-17 18:25:16.117 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) queueBuffer: fps=17.99 dur=1945.35 max=1301.74 min=9.95
05-17 18:25:16.179 I/NotificationService(800): enqueueToast pkg=io.lerk.lrkFM callback=android.app.ITransientNotification$Stub$Proxy@c1a142 duration=0
05-17 18:25:16.299 I/BufferQueueProducer(224): [Toast](this:0xab426000,id:1362,api:1,p:16738,c:224) connect(P): api=1 producer=(16738:io.lerk.lrkFM) producerControlledByApp=true
05-17 18:25:17.765 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) queueBuffer: fps=21.84 dur=1648.49 max=960.88 min=16.40
05-17 18:25:18.400 W/io.lerk.lrkFM(16738): type=1400 audit(0.0:3627): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
05-17 18:25:18.411 W/io.lerk.lrkFM.activities.FileActivity(16738): Can't read '/': Permission denied!
05-17 18:25:18.415 I/NotificationService(800): enqueueToast pkg=io.lerk.lrkFM callback=android.app.ITransientNotification$Stub$Proxy@5cc8f8e duration=0
05-17 18:25:18.475 I/BufferQueueProducer(224): [Toast](this:0xaee5e000,id:1363,api:1,p:16738,c:224) connect(P): api=1 producer=(16738:io.lerk.lrkFM) producerControlledByApp=true
05-17 18:25:18.769 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) queueBuffer: fps=38.87 dur=1003.45 max=314.57 min=10.79
05-17 18:25:20.577 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:224) queueBuffer: fps=8.85 dur=1808.30 max=1542.44 min=15.54
05-17 18:25:20.660 W/io.lerk.lrkFM.activities.FileActivity(16738): Can't read 'null': Permission denied!
05-17 18:25:20.650 W/io.lerk.lrkFM(16738): type=1400 audit(0.0:3628): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
05-17 18:25:20.669 E/UncaughtException(16738): 	at io.lerk.lrkFM.activities.FileActivity.setToolbarText(FileActivity.java:625)
05-17 18:25:20.669 E/UncaughtException(16738): 	at io.lerk.lrkFM.activities.FileActivity.loadDirectory(FileActivity.java:530)
05-17 18:25:20.669 E/UncaughtException(16738): 	at io.lerk.lrkFM.activities.FileActivity.loadPath(FileActivity.java:489)
05-17 18:25:20.669 E/UncaughtException(16738): 	at io.lerk.lrkFM.activities.FileActivity.lambda$onCreate$0(FileActivity.java:287)
05-17 18:25:20.669 E/UncaughtException(16738): 	at io.lerk.lrkFM.activities.-$$Lambda$FileActivity$dpy7EQyvdu2Ux2xwJIRa8f1z6FU.onClick(lambda)
05-17 18:25:21.083 E/AndroidRuntime(16738): Process: io.lerk.lrkFM, PID: 16738
05-17 18:25:21.083 E/AndroidRuntime(16738): 	at io.lerk.lrkFM.activities.FileActivity.setToolbarText(FileActivity.java:625)
05-17 18:25:21.083 E/AndroidRuntime(16738): 	at io.lerk.lrkFM.activities.FileActivity.loadDirectory(FileActivity.java:530)
05-17 18:25:21.083 E/AndroidRuntime(16738): 	at io.lerk.lrkFM.activities.FileActivity.loadPath(FileActivity.java:489)
05-17 18:25:21.083 E/AndroidRuntime(16738): 	at io.lerk.lrkFM.activities.FileActivity.lambda$onCreate$0(FileActivity.java:287)
05-17 18:25:21.083 E/AndroidRuntime(16738): 	at io.lerk.lrkFM.activities.-$$Lambda$FileActivity$dpy7EQyvdu2Ux2xwJIRa8f1z6FU.onClick(lambda)
05-17 18:25:21.093 W/ActivityManager(800):   Force finishing activity io.lerk.lrkFM/.activities.FileActivity
05-17 18:25:21.174 I/BufferQueueConsumer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:0,p:-1,c:224) setConsumerName: Application Error: io.lerk.lrkFM
05-17 18:25:21.174 I/BufferQueueConsumer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:0,p:-1,c:224) setDefaultBufferSize: width=129 height=129
05-17 18:25:21.186 I/BufferQueueConsumer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:0,p:-1,c:224) setDefaultBufferSize: width=812 height=512
05-17 18:25:21.198 I/BufferQueueProducer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:800,c:224) connect(P): api=1 producer=(800:system_server) producerControlledByApp=false
05-17 18:25:21.207 I/AEE_AED (16825): [preset_info] pid: 16738, tid: -1361051648, name: UNKNOWN  >>> io.lerk.lrkFM <<<
05-17 18:25:21.214 I/BufferQueueProducer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:800,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-17 18:25:21.219 I/BufferQueueProducer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:800,c:224) new GraphicBuffer needed
05-17 18:25:21.243 I/BufferQueueProducer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:800,c:224) new GraphicBuffer needed
05-17 18:25:21.604 W/ActivityManager(800): Activity pause timeout for ActivityRecord{a03d007 u0 io.lerk.lrkFM/.activities.FileActivity t2544 f}
05-17 18:25:21.605 I/PPS     (800): [PPSNotifyAppState] pack:io.lerk.lrkFM, com:io.lerk.lrkFM.activities.FileActivity, state:0,ActiveCount = 0
05-17 18:25:21.605 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:io.lerk.lrkFM, com:io.lerk.lrkFM.activities.FileActivity, state:0, pid:16738, last_boost_tid:16738
05-17 18:25:23.432 W/ActivityManager(800):   Force finishing activity io.lerk.lrkFM/.activities.FileActivity
05-17 18:25:23.433 I/WindowManager(800): Destroying surface Surface(name=io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.removeLocked:1469 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2678 com.android.server.wm.WindowManagerService.removeWindowLocked:2626 com.android.server.wm.WindowManagerService.removeWindowLocked:2489 com.android.server.wm.AppWindowToken.removeAllWindows:539 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:335 
05-17 18:25:23.437 I/BufferQueueProducer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:-1,c:224) disconnect(P): api 1
05-17 18:25:23.438 I/BufferQueueConsumer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-17 18:25:23.452 I/BufferQueueConsumer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:16738,c:-1) disconnect(C)
05-17 18:25:23.456 I/ActivityManager(800): Killing 16738:io.lerk.lrkFM/u0a216 (adj 906): crash
05-17 18:25:23.472 W/ViewRootImpl[lrkFM](800): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=487.29822, y[0]=562.192, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=2, eventTime=69286306, downTime=69286278, deviceId=2, source=0x1002 }
05-17 18:25:23.512 I/WindowManager(800): Destroying surface Surface(name=Application Error: io.lerk.lrkFM) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:434 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:235 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:183 com.android.server.wm.WindowManagerService$H.handleMessage:8464 android.os.Handler.dispatchMessage:110 
05-17 18:25:23.523 I/BufferQueueConsumer(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:-1,c:-1) disconnect(C)
05-17 18:25:23.523 I/BufferQueue(224): [Application Error: io.lerk.lrkFM](this:0xaee5e000,id:1364,api:1,p:-1,c:-1) ~BufferQueueCore
05-17 18:25:23.533 I/BufferQueueProducer(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:-1,c:-1) disconnect(P): api 1
05-17 18:25:23.534 I/BufferQueue(224): [io.lerk.lrkFM/io.lerk.lrkFM.activities.FileActivity](this:0xab472000,id:1359,api:1,p:-1,c:-1) ~BufferQueueCore

```

**Comment by lfuelling** [comment]
😱
