### ISSUE TITLE
Made the app crash when trying to delete a folder

### ISSUE THREAD

**Issue by shaphir** [lfuelling/lrkFM#17]
Hello developers. 

After opening the app, i hope through this app can allow me to delete some junk folder. But, when I try to delete some folders there, the folder can not be deleted and the app becomes crashed.

1. Open the app
2. After opening the app, there will be some of your folders there, press the dotted feature that is in front of the folder, then there will be delete feature
3. After pressing delete, the app will crash, and the folder cannot be deleted.

rkFM app version 1.6.4
Operating system by Oppo a57 android version 6.0.1

Video recording bugs on youtube
https://youtu.be/emH8KETw0Js

**Comment by shaphir** [comment]
Maybe you should also try it on android 6.0

**Comment by mcyusuf** [comment]
The PO would look into that. I don't have a 6.0 emulator or device. Would have tested on 5.1 but app isn't supported on that version.

**Comment by lfuelling** [comment]
Yes, sorry that I don't support Lollipop, but I wanted to have at least lambdas available while coding 😬 

Unfortunately I only tested the app on 8.x and 9(?) because that are the physical devices I own. From now on I will also test with 7 and 6 in emulator. Sorry for the inconvenience. And thanks a lot to you who report all the bugs! ❤️

**Comment by mcyusuf** [comment]
It's cool, keep up the good work.

**Comment by lfuelling** [comment]
@shaphir the following gif is taken with the android 6.0 emulator.

![deletion](https://user-images.githubusercontent.com/5144843/40242663-7e7df420-5abe-11e8-9456-5be8f7bfe665.gif)

Could it be that you (either the `android` user on the phone or the app) don't have write permissions for the folder you're trying to delete?

**Comment by shaphir** [comment]
If true as you say, but the app crashes.

**Comment by tobias-g1** [comment]
Was able to replicate on 7.0, I think the issue is that permissions are being denied (this hasn't been noted in the steps to reproduce). 

```

05-18 18:57:58.649 4436-4436/io.lerk.lrkFM E/UncaughtException: java.lang.NullPointerException: Attempt to get length of null array
        at io.lerk.lrkFM.op.OperationUtil.deleteNoValidation(OperationUtil.java:155)
        at io.lerk.lrkFM.util.ContextMenuUtil.lambda$null$1(ContextMenuUtil.java:92)
        at io.lerk.lrkFM.util.-$$Lambda$ContextMenuUtil$DGIoYV7vaPZdxJWSIC0EvUmD03I.onClick(lambda)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:164)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
05-18 18:57:58.696 4436-4436/io.lerk.lrkFM E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.lerk.lrkFM, PID: 4436
    java.lang.NullPointerException: Attempt to get length of null array
        at io.lerk.lrkFM.op.OperationUtil.deleteNoValidation(OperationUtil.java:155)
        at io.lerk.lrkFM.util.ContextMenuUtil.lambda$null$1(ContextMenuUtil.java:92)
        at io.lerk.lrkFM.util.-$$Lambda$ContextMenuUtil$DGIoYV7vaPZdxJWSIC0EvUmD03I.onClick(lambda)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:164)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

```

**Comment by lfuelling** [comment]
I added a catch for this, so the app won't crash anymore. But using the app without granting the necessary permissions is obviously not supported. 😁
